# (C) Copyright 2024, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/private-west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: sorru94
      url-base: https://github.com/sorru94

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.2.0-rc2
      import: true
    - name: zlib-zephyr
      remote: sorru94
      revision: release-v1.3.1-no-crc32
      path: modules/zlib
