# (C) Copyright 2024, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/private-west-commands.yml

  remotes:
    - name: sorru94
      url-base: https://github.com/sorru94
    - name: secomind
      url-base: https://github.com/secomind


  projects:
    - name: zephyr
      remote: sorru94
      revision: heap-listeners
      import: true
    - name: zlib-zephyr
      remote: secomind
      revision: release-v1.3.1
      path: modules/zlib
