# (C) Copyright 2024, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

"""astarte-interfaces.py

West extension that can be used to generate interfaces definitions.

Checked using pylint with the following command (pip install pylint):
python -m pylint --rcfile=./scripts/.pylintrc ./scripts/*.py
Formatted using black with the following command (pip install black):
python -m black --line-length 100 ./scripts/*.py
"""

from pathlib import Path
from textwrap import dedent

from west.commands import WestCommand

from astarte_interfaces.generator import generate_interfaces


class WestCommandAstarteInterfaces(WestCommand):
    """Extension of the WestCommand class, specific for this command."""

    def __init__(self):
        super().__init__(
            "astarte-interfaces",
            "Generate interfaces header(s)",
            dedent("""Generates C interfaces definitions from .json definitions."""),
        )

    def do_add_parser(self, parser_adder):
        """
        This function can be used to add custom options for this command.
        Allows you full control over the type of argparse handling you want.

        Parameters
        ----------
        parser_adder : Any
            Parser adder generated by a call to `argparse.ArgumentParser.add_subparsers()`.

        Returns
        -------
        argparse.ArgumentParser
            The argument parser for this command.
        """
        parser = parser_adder.add_parser(self.name, help=self.help, description=self.description)
        parser.add_argument("json_dir", help="Directory containing the interfaces .json file(s).")
        parser.add_argument(
            "-p",
            "--output_prefix",
            help="Prefix to add to all generated sources. Defaults to no prefix if not specified.",
            type=str,
            default="",
        )
        parser.add_argument(
            "-d",
            "--output_dir",
            help="Directory where the generated headers will be stored. "
            "Defaults to json_dir if not specified.",
            default=None,
        )
        parser.add_argument(
            "-c",
            "--check",
            help="Check if previously generated interfaces are up to date.",
            action="store_true",
        )
        return parser

    def do_run(self, args, _unknown_args):
        """
        Function called when the user runs the custom command, e.g.:

          $ west astarte-interfaces ...

        Parameters
        ----------
        args : Any
            Arguments pre parsed by the parser defined by `do_add_parser()`.
        """
        interfaces_dir = Path(args.json_dir).absolute()
        output_dir = Path(args.output_dir).absolute() if args.output_dir else interfaces_dir
        output_filename = args.output_prefix + "generated_interfaces"

        generate_interfaces(interfaces_dir, output_dir, output_filename, args.check)
