# (C) Copyright 2024, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

"""clean.py

West extension that can be used to clean temporary build artifacts.

Checked using pylint with the following command (pip install pylint):
python -m pylint --rcfile=./scripts/.pylintrc ./scripts/*.py
Formatted using black with the following command (pip install black):
python -m black --line-length 100 ./scripts/*.py
"""

import shutil
from pathlib import Path

from textwrap import dedent
from colored import fore, stylize
from west.commands import WestCommand


class WestCommandClean(WestCommand):
    """Extension of the WestCommand class, specific for this command."""

    def __init__(self):
        super().__init__(
            "clean",
            "Clean build artifacts",
            dedent("""Convenience wrapper to clean temporary build artifacts."""),
        )

    def do_add_parser(self, parser_adder):
        """
        This function could be used to add custom options for this command.

        Parameters
        ----------
        parser_adder : Any
            Parser adder generated by a call to `argparse.ArgumentParser.add_subparsers()`.

        Returns
        -------
        argparse.ArgumentParser
            The argument parser for this command.
        """
        parser = parser_adder.add_parser(self.name, help=self.help, description=self.description)
        return parser

    def do_run(self, _args, _unknown_args):
        """
        Function called when the user runs the custom command, e.g.:

          $ west clean

        """

        workspace_path = Path(self.manifest.topdir)
        library_path = Path(self.manifest.repo_abspath)
        build_dirs = (
            [
                workspace_path.joinpath("build"),
                library_path.joinpath("build"),
                library_path.joinpath("doc").joinpath("_build"),
                library_path.joinpath("e2e").joinpath("build"),
            ]
            + list(Path(workspace_path).glob("twister-out*"))
            + list(Path(library_path).glob("twister-out*"))
            + list(Path(library_path).joinpath("e2e").glob("twister-out*"))
        )
        for build_dir in build_dirs:
            if build_dir.is_dir():
                self.inf(stylize(f"Removing directory: {build_dir}", fore("cyan")))
                shutil.rmtree(build_dir)
