# (C) Copyright 2024, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

"""docs.py

West extension that can be used to build doxygen documentation for this project.

Checked using pylint with the following command (pip install pylint):
python -m pylint --rcfile=./scripts/.pylintrc ./scripts/*.py
Formatted using black with the following command (pip install black):
python -m black --line-length 100 ./scripts/*.py
"""

import os
import subprocess
import shutil
from pathlib import Path

from textwrap import dedent
from colored import fore, stylize
from west.commands import WestCommand


class WestCommandDocs(WestCommand):
    """Extension of the WestCommand class, specific for this command."""

    def __init__(self):
        super().__init__(
            "docs",
            "Generate documentation (doxygen)",
            dedent("""Convenience wrapper to build documentation with doxygen."""),
        )

    def do_add_parser(self, parser_adder):
        """
        This function can be used to add custom options for this command.
        Allows you full control over the type of argparse handling you want.

        Parameters
        ----------
        parser_adder : Any
            Parser adder generated by a call to `argparse.ArgumentParser.add_subparsers()`.

        Returns
        -------
        argparse.ArgumentParser
            The argument parser for this command.
        """
        parser = parser_adder.add_parser(self.name, help=self.help, description=self.description)
        parser.add_argument(
            "-c", "--clean", help="clean previous documentation", action="store_true"
        )
        parser.add_argument(
            "-e",
            "--extended",
            help="Generate an extended version of the documentation. "
            "If active, the documentation will be generated also for private include files.",
            action="store_true",
        )
        return parser

    def _run_cmd(self, cmd, cwd, env=None):
        """
        Helper to run a subprocess command and print it.

        Parameters
        ----------
        cmd : list of str
            The command to be executed, provided as a list of strings.
        cwd : Path or str
            The current working directory where the command should be executed.
        env : dict, optional
            Environment variables to pass to the subprocess. Defaults to os.environ.
        """
        cmd_str = " ".join(cmd)
        self.inf(stylize(cmd_str, fore("cyan")))
        subprocess.run(
            cmd,
            cwd=cwd,
            timeout=300,
            check=True,
            env=env if env else os.environ,
        )

    def do_run(self, args, _unknown_args):
        """
        Function called when the user runs the custom command, e.g.:

          $ west docs

        Parameters
        ----------
        args : Any
            Arguments pre parsed by the parser defined by `do_add_parser()`.
        """
        repo_root = Path(self.manifest.repo_abspath)
        doc_source_dir = repo_root / "doc"
        build_dir = doc_source_dir / "_build"
        env = dict(os.environ)

        if args.clean:
            if build_dir.exists():
                self.inf(f"Cleaning build directory: {build_dir}")
                shutil.rmtree(build_dir)
            else:
                self.inf("Clean requested, but build directory does not exist.")

        configure_cmd = [
            "cmake",
            "-GNinja",
            f"-B{build_dir}",
            f"-S{doc_source_dir}",
            f"-DDOXYGEN_LIBRARY_PATH={repo_root}",
            f"-DEXTENDED_DOCS={'yes' if args.extended else 'no'}",
        ]
        self._run_cmd(configure_cmd, cwd=repo_root, env=env)

        build_cmd = [
            "cmake",
            "--build",
            str(build_dir),
            "--target",
            "library_documentation",
        ]
        self._run_cmd(build_cmd, cwd=repo_root, env=env)
