# (C) Copyright 2024, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

"""docs.py

West extension that can be used to build doxygen documentation for this project.

Checked using pylint with the following command (pip install pylint):
python -m pylint --rcfile=./scripts/.pylintrc ./scripts/*.py
Formatted using black with the following command (pip install black):
python -m black --line-length 100 ./scripts/*.py
"""

import os
import subprocess
from pathlib import Path

from textwrap import dedent
from colored import fore, stylize
from west.commands import WestCommand


class WestCommandDocs(WestCommand):
    """Extension of the WestCommand class, specific for this command."""

    def __init__(self):
        super().__init__(
            "docs",
            "Generate documentation (doxygen)",
            dedent("""Convenience wrapper to buld documentation with doxygen."""),
        )

    def do_add_parser(self, parser_adder):
        """
        This function can be used to add custom options for this command.
        Allows you full control over the type of argparse handling you want.

        Parameters
        ----------
        parser_adder : Any
            Parser adder generated by a call to `argparse.ArgumentParser.add_subparsers()`.

        Returns
        -------
        argparse.ArgumentParser
            The argument parser for this command.
        """
        parser = parser_adder.add_parser(self.name, help=self.help, description=self.description)
        parser.add_argument(
            "-c", "--clean", help="clean previous documentation", action="store_true"
        )
        parser.add_argument(
            "-e",
            "--extended",
            help="Generate an extended version of the documentation. "
            "If active, the documentation will be generated also for private include files.",
            action="store_true",
        )
        return parser

    def do_run(self, args, _unknown_args):
        """
        Function called when the user runs the custom command, e.g.:

          $ west docs

        Parameters
        ----------
        args : Any
            Arguments pre parsed by the parser defined by `do_add_parser()`.
        """
        library_path = Path(self.manifest.repo_abspath)
        if args.clean:
            build_path = os.path.join(library_path, "doc", "_build")
            if os.path.exists(build_path):
                make_clean_cmd = "make -C doc clean"
                self.inf(stylize(make_clean_cmd, fore("cyan")))
                subprocess.run(
                    make_clean_cmd,
                    shell=True,
                    cwd=library_path,
                    timeout=60,
                    check=True,
                    env=dict(
                        os.environ,
                        LIBRARY_PATH=f"{library_path}",
                        EXTENDED_DOCS="yes" if args.extended else "no",
                    ),
                )
        make_docs_cmd = "make -C doc doxygen"
        self.inf(stylize(make_docs_cmd, fore("cyan")))
        subprocess.run(
            make_docs_cmd,
            shell=True,
            cwd=library_path,
            timeout=60,
            check=True,
            env=dict(
                os.environ,
                LIBRARY_PATH=f"{library_path}",
                EXTENDED_DOCS="yes" if args.extended else "no",
            ),
        )
