# (C) Copyright 2024, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

"""format.py

West extension that can be used to run  automatic source code formatting.

Checked using pylint with the following command (pip install pylint):
python -m pylint --rcfile=./scripts/.pylintrc ./scripts/*.py
Formatted using black with the following command (pip install black):
python -m black --line-length 100 ./scripts/*.py
"""

import subprocess

from textwrap import dedent
from pathlib import Path
from colored import stylize, fg
from west.commands import WestCommand


class WestCommandFormat(WestCommand):
    """Extension of the WestCommand class, specific for this command."""

    def __init__(self):
        super().__init__(
            "format",
            "Format the source files (clang-format)",
            dedent("""Convenience wrapper for formatting the source files."""),
        )

    def do_add_parser(self, parser_adder):
        """
        This function can be used to add custom options for this command.
        Allows you full control over the type of argparse handling you want.

        Parameters
        ----------
        parser_adder : Any
            Parser adder generated by a call to `argparse.ArgumentParser.add_subparsers()`.

        Returns
        -------
        argparse.ArgumentParser
            The argument parser for this command.
        """
        parser = parser_adder.add_parser(self.name, help=self.help, description=self.description)
        parser.add_argument(
            "-d",
            "--dry-run",
            help="If set, do not actually make the formatting changes",
            action="store_true",
        )
        return parser

    def do_run(self, args, _unknown_args):
        """
        Function called when the user runs the custom command, e.g.:

          $ west format

        Parameters
        ----------
        args : Any
            Arguments pre parsed by the parser defined by `do_add_parser()`.
        """
        library_path = Path(self.manifest.repo_abspath)
        headers_and_sources = [
            str(Path(library_path).joinpath(s))
            for s in (
                "include/**/*.h",
                "lib/**/include/*.h",
                "lib/**/*.c",
                "samples/**/include/*.h",
                "samples/**/src/*.c",
                "tests/lib/**/**/include/*.h",
                "tests/lib/**/**/**/src/*.c",
                "e2e/include/*.h",
                "e2e/src/*.c",
            )
        ]
        for header_or_source in headers_and_sources:
            cmd = ["clang-format", "--dry-run -Werror" if args.dry_run else "-i", header_or_source]
            self.inf(stylize(" ".join(cmd), fg("cyan")))
            subprocess.run(" ".join(cmd), shell=True, cwd=library_path, timeout=60, check=True)
